### ISSUE TITLE
mod_name in mp_load_dynlib

### ISSUE THREAD

**Issue by JunOllyLi** [stinos/micropython#4] opened 2019-04-23 14:58 UTC
Hi,
I was trying to use your code to load some .so modules on Linux and it works. But I had to make some changes.
You required the .so to expose a function names "init_<module_name>()", which works in the scenario of "import module_name". But in a lot of places people do "from pkg_name import module_name", in this scenario, the mod_name passed in to mp_load_dynlib is actually <pkg_name>.<module_name> which makes init_<mod_name> an invalid C function name.
My workaround was to search for the last "." in mod_name and only used the rest of the string to be the init function name.

**Comment by stinos** [comment] 2019-04-23 15:42
Good find. Can you provide some more information on how to reproduce this? I'd mainly need to know what your directory structure looks like, e.g. do you have something like
```
/path/to/pkg_name
                 /__init__.py
                 /mod_name.so
```
or something different?

**Comment by JunOllyLi** [comment] 2019-04-23 16:29
What I had is
/path/to/
         caller.py
         /pkg_name
                 /__init__.py
                 /py_module.py
                 /c_module.so

In caller.py I did "from pkg_name import py_module", and in py_module.py there is "from pkg_name import c_module"

py_module.py was not written by me, I was just trying to port existing CPython module to micropython.

**Comment by stinos** [comment] 2019-04-25 15:52
An easier solution than looking for the "." is to change the call to `mp_load_dynlib()` in builtinimport.c like this:

```
mp_obj_module_t* module_ptr = mp_load_dynlib(mod_str + last, &path);
```

then it automatically passes the last part of the name.

There's another problem though, slightly related: we're expecting the `init_<modulename>()` function to create a new module object so it likely does that by `using mp_obj_new_module()` and so it sets the module name. However that name will be wrong in case of relative imports (e.g. in your example `py_module.__name__` will probably be "my_module" but that should actually be "pkg_name.my_module". This can be fixed by adding
```
mp_obj_dict_store(MP_OBJ_FROM_PTR(module_ptr->globals), MP_OBJ_NEW_QSTR(MP_QSTR___name__), MP_OBJ_NEW_QSTR(mod_name));
```

in builtinimport.c after `mp_load_dyn_lib()`. Could you test both fixes and check if they work for you, then I can merge them?

> BTW. How do you indent the text like you did to show the folder structure?

Using markdown syntax and surrounding that text with ` ``` `. In the lower right corner of the box where you write text, right above the 'Comment' button, there's a M symbol which is a link to documentation for that syntax.

**Comment by JunOllyLi** [comment] 2019-04-26 04:49
1. The change to call mp_load_dynlib works! That is better than my workaround. :)
2. For the name in returned mp_obj_module_t, that line of change seems crashed. There was no crashing info, but just never went to the line following that.
```
                mp_obj_module_t* module_ptr = mp_load_dynlib(mod_str + last, &path);
                if (module_ptr == NULL) {
                    nlr_raise(mp_obj_new_exception_msg_varg(&mp_type_ImportError, "Module load failed for '%s'", qstr_str(mod_name)));
                }
                printf("+++++++\n");
                mp_obj_dict_store(MP_OBJ_FROM_PTR(module_ptr->globals), MP_OBJ_NEW_QSTR(MP_QSTR___name__), MP_OBJ_NEW_QSTR(mod_name));
                printf("-------\n");
```
I saw the first printed out plus signs but never seen the minors signs. Python code calling the import did fail with no TypeError though.

**Comment by JunOllyLi** [comment] 2019-04-27 04:06
This seems working:
```
        mp_store_attr(module_ptr, MP_QSTR___name__, MP_OBJ_NEW_QSTR(mod_name));
```

**Comment by stinos** [comment] 2019-04-29 07:44
Can you show the C code which creates the module?

**Comment by JunOllyLi** [comment] 2019-04-30 04:20
Sure. Here is (part of) my experiment code to implement the subprocess stuff:

STATIC mp_obj_t _waitpid(mp_obj_t opid) {
    mp_obj_t rvalue = mp_const_none;
    
    pid_t pid = mp_obj_get_int(opid);
    //printf("%s %d\n", __FUNCTION__, pid);
    int stat = 0;
    waitpid(pid, &stat, 0);

    return rvalue;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_1(_waitpid_obj, _waitpid);

mp_obj_module_t *init__subprocess() {
    printf("%s\n", __FUNCTION__);
    qstr name = qstr_from_str("_subprocess");
    mp_obj_t m = mp_obj_new_module(name);
    mp_store_attr(m, qstr_from_str("check_output"), (mp_obj_t)&check_output_obj);
    mp_store_attr(m, qstr_from_str("fork"), (mp_obj_t)&_fork_obj);
    mp_store_attr(m, qstr_from_str("waitpid"), (mp_obj_t)&_waitpid_obj);
    mp_store_name(name, m);

    return m;
}

**Comment by stinos** [comment] 2019-05-02 16:59
That is strange. I tried your code and cannot reproduce the problem, moreover the result of both ways of storing the name are the same for me: in objdict.c line 596 I added this line to see what gets stored:
```
printf("dict_store key %p value %p -> %p\n", key, value, self_in);
```
then when using this:
```
printf("mp_obj_dict_store\n");
mp_obj_dict_store(MP_OBJ_FROM_PTR(module_ptr->globals), MP_OBJ_NEW_QSTR(MP_QSTR___name__), MP_OBJ_NEW_QSTR(mod_name));
printf("mp_store_attr\n");
mp_store_attr(module_ptr, MP_QSTR___name__, MP_OBJ_NEW_QSTR(mod_name));
```
the output is the same for both (but the first would be slightly faster because it's more direct):
```
mp_obj_dict_store
dict_store key 5e value a72 -> 7f17cb5bb8e0
mp_store_attr
dict_store key 5e value a72 -> 7f17cb5bb8e0
```

Not sure what could cause the problem for you. Maybe something in code you're not showing, or different compiler flags or so?

For reference this is what I am doing:
```
> cat _subprocess.c
#include "runtime.h"
#include "objfun.h"
#include "objmodule.h"
#include "qstr.h"
#include <stdio.h>

static mp_obj_t _waitpid(mp_obj_t a) {
	return mp_const_none;
}
static MP_DEFINE_CONST_FUN_OBJ_1(_waitpid_obj, _waitpid);

mp_obj_module_t *init__subprocess() {
	printf("%s\n", __FUNCTION__);
	qstr name = qstr_from_str("_subprocess");
	mp_obj_t m = mp_obj_new_module(name);
	mp_store_attr(m, qstr_from_str("waitpid"), (mp_obj_t)&_waitpid_obj);
	mp_store_name(name, m);
	return m;
}

>  gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609

> git -C ../micropython log --pretty=oneline --decorate=short -n1
9f77ae1e61191853c99c267c68c2a291087c7082 (HEAD -> package-import-fix, origin/package-import-fix) fixup! py: Make import recognize and load native modules (.pyd or .so files)

> make -C ../micropython/ports/unix MICROPY_PY_BTREE=0 MICROPY_PY_FFI=0 MICROPY_PY_USSL=0 MICROPY_PY_AXTLS=0 MICROPY_FATFS=0 MICROPY_PY_THREAD=0
...

> gcc -fPIC -Wall -Werror -I../micropython -I../micropython/py -I../micropython/ports/unix -I../micropython/ports/unix/build -DMICROPY_PY_THREAD=0 -c _subprocess.c -o _subprocess.o

> gcc -shared -o _subprocess.so _subprocess.o

> mkdir -p ~/.micropython/lib/mypackage

> cp _subprocess.so ~/.micropython/lib/mypackage/_subprocess.so
```

**Comment by JunOllyLi** [comment] 2019-05-02 20:34
Emm...not sure what went wrong. It could be the compiler difference. I was compiling it on an ARM device (Lego EV3 brick) with ev3dev Debian-Stretch image

**Comment by stinos** [comment] 2019-05-07 07:12
Do you still have the issue, also after trying with simple code like shown above?
If so is there any way i can try this out myself, i.e. can I run this on an emulator or so?

**Comment by JunOllyLi** [comment] 2019-05-08 04:06
Well, I just got a new SD card with fresh flashed ev3dev image and your code works! Maybe something went wrong with my device last time. :)

**Comment by stinos** [comment] 2019-05-09 11:14
Sounds good :)
This change is now in the main windows_pyd branch.

**Closed by stinos** 2019-05-09 11:14 UTC
